version: "3.9"

services:

  database:
    image: postgres:14.4
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=website
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge